base_config: ./config/
base_expid: DCNv3_KKBox_x10
dataset_id: KKBox_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 10000
    embedding_regularizer: 1.e-3
    num_cross_layers: [1, 2, 3, 4, 5, 6]
    net_dropout: [0.1, 0.2, 0.3]

