base_config: ./config/
base_expid: DCNv3_Criteo
dataset_id: Criteo_x4_10_h5

tuner_space:
    model_root: './checkpoints/'
    batch_size: 4096
    num_cross_layers: [1, 2, 3, 4, 5, 6]
    net_dropout: [0.1]

