base_config: ./config/
base_expid: SDCNv3_KKBox_x10
dataset_id: KKBox_csv

tuner_space:
    model_root: './checkpoints/'
    batch_size: 10000
    num_deep_cross_layers: [3, 4, 5]
    num_shallow_cross_layers: [2, 3, 4, 5]
    deep_net_dropout: [0.1, 0.2, 0.3]
    shallow_net_dropout: [0.1, 0.2, 0.3]
